### ISSUE TITLE
Error with Java Runtime on 1.19.3

### ISSUE THREAD

**Issue by sternschnaube** [y2k04/cbp#1]
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.UnsupportedClassVersionError: net/minecraft/class_7264 has been compiled by a more recent version of the Java Runtime (class file version 62.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/class_7264 has been compiled by a more recent version of the Java Runtime (class file version 62.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.entity.EntityType.<clinit>(EntityType:182)
	at net.minecraft.item.Items.<clinit>(Items:764)
	at net.minecraft.block.LightBlock.getOutlineShape(LightBlock:56)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:887)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getOutlineShape(AbstractBlock:883)
	at net.minecraft.block.AbstractBlock.getCollisionShape(AbstractBlock:354)
	at net.minecraft.block.AbstractBlock$AbstractBlockState$ShapeCache.<init>(AbstractBlock:1155)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.initShapeCache(AbstractBlock:740)
	at net.minecraft.block.Blocks.<clinit>(Blocks:1132)
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock:325)
	at net.minecraft.Bootstrap.initialize(Bootstrap:46)
	at net.minecraft.client.main.Main.main(Main:161)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more

**Comment by y2k04** [comment]
Oh oops, let me recompile it on an older version! I apologise!

**Comment by venaminecraft** [comment]
Thank you 😊

**Comment by y2k04** [comment]
Done :3
[https://github.com/y2k04/cbp/releases/tag/v1.0.3](https://github.com/y2k04/cbp/releases/tag/v1.0.3)

**Comment by venaminecraft** [comment]
Works 🥳
